spring:
  application:
    name: spring-k8s-configapp
  cloud:
    kubernetes:
      reload:
        enabled: true

management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
  
server:
  port: 8080
  
logging:
  level:
    root: debug
  
