apiVersion : apps/v1
kind: Deployment
metadata:
  name: spring-k8s-configmap
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-k8s-configmap
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spring-k8s-configmap
    spec:
      containers:
        - name: spring-k8s-configmap 
          image: spring-k8s-configmap:0.0.1
          imagePullPolicy: Never
          ports:
          - containerPort: 8080
