apiVersion: rbac.authorization.k8s.io/v1
kind: Role 
metadata:
  name: spring-k8s-aws-sm
  namespace: ns-sample
rules:
- apiGroups:
  - ""
  resources:
  - services
  - pods
  - endpoints
  - namespaces
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
  
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spring-k8s-aws-sm
  namespace: ns-sample
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spring-k8s-aws-sm
subjects:
- kind: ServiceAccount
  name: default
  namespace: ns-sample